### ISSUE TITLE
Huh? (permission change)

### ISSUE THREAD

**Issue by checkraisefold** [arthurbolsoni/Purple-adblock#21]
![image](https://user-images.githubusercontent.com/19525688/121799477-3ad43d00-cbe1-11eb-9be9-8703fcd3f20f.png)

**Comment by checkraisefold** [comment]
![image](https://user-images.githubusercontent.com/19525688/121799736-981cbe00-cbe2-11eb-9dbe-ae0a8abcc340.png)
![image](https://user-images.githubusercontent.com/19525688/121799741-9b17ae80-cbe2-11eb-9b58-45271911dd4c.png)

**Comment by anastalaz** [comment]
Yeah something fishy is going on here. Found this new listener in the source code calling some amazon adserver and remote javascript:

`
chrome.webRequest.onBeforeRequest.addListener(
    onBeforeRequest, {
        urls: ["https://*.amazon-adsystem.com/*", "https://cdn.krxd.net/*", "https://script.ioam.de/iam.js", "https://edge.quantserve.com/quant.js", "https://ddacn6pr5v0tl.cloudfront.net/*", "https://d2v02itv0y9u9t.cloudfront.net/dist/1.0.5/v6s.js", "https://*.imrworldwide.com/*", "https://countess.twitch.tv/*", "https://*.scorecardresearch.com/*", "https://www.googletagservices.com/tag/js/gpt.js", "*://*.branch.io/*", "*://comscore.com/*", "https://usher.ttvnw.net/api/channel/hls/*"]
    },
    ["blocking", "extraHeaders"]
);
`

DO NOT ENABLE THE PLUGIN!!!

**Comment by checkraisefold** [comment]
> Yeah something fishy is going on here. Found this new listener in the source code calling some amazon adserver and remote javascript:
> 
> `chrome.webRequest.onBeforeRequest.addListener( onBeforeRequest, { urls: ["https://*.amazon-adsystem.com/*", "https://cdn.krxd.net/*", "https://script.ioam.de/iam.js", "https://edge.quantserve.com/quant.js", "https://ddacn6pr5v0tl.cloudfront.net/*", "https://d2v02itv0y9u9t.cloudfront.net/dist/1.0.5/v6s.js", "https://*.imrworldwide.com/*", "https://countess.twitch.tv/*", "https://*.scorecardresearch.com/*", "https://www.googletagservices.com/tag/js/gpt.js", "*://*.branch.io/*", "*://comscore.com/*", "https://usher.ttvnw.net/api/channel/hls/*"] }, ["blocking", "extraHeaders"] );`
> 
> DO NOT ENABLE THE PLUGIN!!!

This doesn't seem very fishy; might be blocking these? these look like they are related to analytics and ad-serving

**Comment by anastalaz** [comment]
Yes these are tracking servers and I don't know either if it will block or serve ads. I would have to go through the whole source code to find out.

The fishy part is that the plugin updated in the web store before github. It should be the other way around if this is an open source project.

I uninstalled the plugin and will be waiting for a comment from @arthurbolsoni

**Comment by pixeltris** [comment]
https://robwu.nl/crxviewer/?crx=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fpurple-adblock%2Flkgcfobnmghhbhgekffaadadhmeoindg&qf=js/background.js

That's the code up on the chrome store. It doesn't actually do anything with those new urls. In the `onBeforeRequest` handler it only does stuff with the m3u8 request.

It looks like the urls were copied / pasted from here https://github.com/saucettv/VideoAdBlockForTwitch/blob/main/firefox/background.js

@arthurbolsoni these urls aren't necessary. It's expected people will be using something like uBlock Origin in combination which should already take care of these kind of things.

**Comment by extesy** [comment]
Even if these urls don't do anything (yet), the key moment is that the published extension is different from the source code here. There were extra changes made which nobody knew of but thankfully Chrome caught them. However, this also means that the author can make javascript changes in the future without a corresponding commit. I don't think I can trust this developer ever again.

**Comment by pixeltris** [comment]
There's no malicious intent as far as I can see. Code was copied / pasted and @arthurbolsoni clearly wrongly assumed it would help with the issue of people getting ads lately https://github.com/pixeltris/TwitchAdSolutions/issues/40#issuecomment-859375882

I assume the extension push was to try and get a "fix" out ASAP and likely didn't even think about github. These processes aren't tied together. You can forget to do one without doing the other.

**Comment by rocky134** [comment]
I don't seem to have the permission change in the original post but today this extension seems to have updated to request reading my browsing history?!?
Seems shady that a m3u8 proxy would need access to browser history when it didn't before and neither does ttv lol.
Seems almost like an attempt at data harvesting users.
![image](https://user-images.githubusercontent.com/34631288/121812930-e3ad8700-cc37-11eb-8080-f3703fd75f2b.png)

**Comment by pixeltris** [comment]
@rocky134 that should have always been there. "tabs" gives that permission requirement which has been in the code since the initial commit:

https://github.com/arthurbolsoni/Purple-adblock/blob/cdb6a71e8350a0b961f2ee65eb90fb42af4658f8/chrome/manifest.json#L27

Refer to the docs on permission requirements:

https://developer.chrome.com/docs/extensions/mv3/permission_warnings/#tabs

It looks like the `chrome.tabs` object is used here:

https://github.com/arthurbolsoni/Purple-adblock/blob/cdb6a71e8350a0b961f2ee65eb90fb42af4658f8/chrome/common/js/popup.js#L43

It's used in popup.js to manage the stream whitelist allowing you to view ads on certain streamers.

No harvesting going on. Perhaps read the code?

**Comment by arthurbolsoni** [comment]
very thanks @pixeltris for that explanation.  i updated first the store because i ever forget do it, and do 1 week later. I found
another "bug" too. https://github.com/arthurbolsoni/Purple-adblock/commit/adfdd0c3d71373b7470a23a6bb7e14a664482cef

about the blocks on the list block. I think in some cases the twitch show the ads over the player. but i dont know if these users use adblock or not, then i put to try like : https://github.com/pixeltris/TwitchAdSolutions/issues/40
i can remove and follow the hint of the @pixeltris 

i gonna do a upload on server too later, but i need the app updated. https://github.com/arthurbolsoni/Purple-adblock/commit/15645fcce4772f1069652820d85440d8b4e10b4f

about the "history read" is what the @pixeltris say. i'm new on extension developer.

my apologies for not up the code before. the purpose of i have done that project is the github, didn't know people cared about.

**Comment by pixeltris** [comment]
I guess people looking specifically for a Twitch ad blocker and nothing else would benefit from those urls being blocked.

Perhaps look at this commit which reduces permission requirements by using `declarativeNetRequest` (chrome only) https://github.com/saucettv/VideoAdBlockForTwitch/commit/555cec10ac4cef9067d2ea36563cec8ff2685cd8

**Comment by arthurbolsoni** [comment]
is nice work of the @saucetvv. i gonna do it too and study the anothers ways to do the "tabs"

**Comment by checkraisefold** [comment]
> very thanks @pixeltris for that explanation. i updated first the store because i ever forget do it, and do 1 week later. I found
> another "bug" too. [...]

Thanks for the clarification! Just wanted to make sure nothing weird was going on. Feel free to close the issue as you see fit.

**Comment by saucettv** [comment]
Can confirm, there is nothing bad about this update. The URL's that this extension now blocks will actually prevent non-stitched ads and prevent analytic data from being captured by Twitch. This actually gives users more privacy. The URL's are also blocked by uBlock, I first added them to my extension because people started saying you need to disable uBlock to get the extensions to work, which is simply not true, but people still did it anyway and then wondered why ads started appearing. Take a closer look at the URL's, they are all ad serving scripts or ad trackers. They are being blocked in the background.js file and you will see that by going to Twitch.tv, opening the console and looking at the net requests, they will be red if blocked.

The tabs permission gives a scary description from Chrome, when really all it's used for is to send the extension settings to the background script. 

Makes me laugh actually, this extension has great privacy features and is opensource not only on the extension, but also on the server. Then you have the other m3u8 proxy extension that actually openly sends your Twitch information to their server and nobody complains.
