### ISSUE TITLE
Seems like twitch broke this one

### ISSUE THREAD

**Issue by elightcap** [arthurbolsoni/Purple-adblock#53]
Im not sure where to get logs, but this plugin was working yesterday, 2022-10-30, but is not working today, 2022-10-31.

Twitch streams load indefinitely and eventually error when the plugin is enabled, and load when the plugin is disabled.

**Comment by arthurbolsoni** [comment]
What browser you are using?

**Comment by elightcap** [comment]
sorry, im on firefox, it seems like its working again though

**Comment by 32423d** [comment]
I am having this issue now too. The browser I am using is Firefox stable version 106.0.5.

**Comment by writzx** [comment]
This happened to me once or twice and then when I disabled it for once it would go back to working properly. that was last week.

But also, today seems like twitch is implementing a different system now. 

![pre-rolls](https://cdn.discordapp.com/attachments/821657514823122966/1040215643062026260/image.png)

![mid-rolls](https://cdn.discordapp.com/attachments/821657514823122966/1040216174224474172/image.png)

**Comment by srvazquez** [comment]
I had to disable the Chrome extension because the Stream doesn't start at all, it only appears the loading icon.

**Comment by arthurbolsoni** [comment]
> I had to disable the Chrome extension because the Stream doesn't start at all, it only appears the loading icon.

It could be an incompatibility issue. the script for chrome is working for me. make sure you don't use 2 more "adblock for twitch" at the same time

**Comment by BWMerlin** [comment]
Just got this today, 2:30 of commercial break in progress.

`Opening: maynarde
blocking success: 200
Opening: maynarde
blocking success: 200
Opening: maynarde
blocking success: 200
Opening: maynarde
blocking success: 200`

**Comment by srvazquez** [comment]
This is also happening to me, Chrome browser and sometimes I have to disable the addon because the stream doesn't start at all. This is the Chrome console log

[Purple]:  Stream Type: normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Server loaded normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: external
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 fail
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Server loaded normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: external
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 fail
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Server loaded normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: external
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 fail
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Server loaded normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: external
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 fail
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Server loaded normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: external
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 fail
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Server loaded normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: external
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 fail
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Server loaded normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: normal
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 [Purple]:  Stream Type: external
2a1743b4-49cf-4a81-8216-505487b6aa7f:1 fail

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/issues/60#issuecomment-1416808161

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/issues/60#issuecomment-1416808161
