### ISSUE TITLE
stopped working today

### ISSUE THREAD

**Issue by thisisdumbstuff** [arthurbolsoni/Purple-adblock#60]
stopped working today, some streams just show offline banner even though streamer is live and online. disable this extension and it works fine. using chrome

**Comment by kevin-wellinger** [comment]
confirm this. sound works for me after 20-30 seconds, but the stream is displayed as offline.

workaround:

they added 2 new elements in "video-player__overlay", remove these:

![Screenshot 2023-01-25-182620](https://user-images.githubusercontent.com/67212166/214637912-0d0c4cf9-a8f8-4225-831a-57a7b83b1245.png)

**Comment by arthurbolsoni** [comment]
There may be some "ghost ads" when loading the stream. but are blocked after 1-2 seconds. give me feedback if it's acceptable or it's better to leave a black screen during this time. or maybe even a custom logo in that time.
https://github.com/arthurbolsoni/Purple-adblock/releases/tag/2.5.1

**Comment by RandomErrorMessage** [comment]
Assuming blacking out the ad isn't a giant hacky workaround that would bloat up the code, I'd opt for that instead of displaying the first several seconds. Showing an advertisement, even for 2 seconds, is a form of assault and I instinctively race to close the window to defend myself from this audiovisual attack.

**Comment by eldepor** [comment]
https://github.com/arthurbolsoni/Purple-adblock/issues/59#issuecomment-1421993379

**Comment by arthurbolsoni** [comment]
https://github.com/arthurbolsoni/Purple-adblock/issues/79
